# Generated by Django 4.1.5 on 2023-09-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="newfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_no", models.IntegerField(default=10)),
                ("newfile_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="viewfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vf_computer_no", models.CharField(max_length=10, unique=True)),
                ("vf_description", models.TextField()),
                ("vf_file_opned", models.DateField()),
                ("vf_file_closed", models.DateField()),
                (
                    "file_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fms.newfile"
                    ),
                ),
            ],
        ),
    ]
