# Generated by Django 4.1.5 on 2023-09-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fms", "0002_v_file_alter_newfile_file_no_delete_viewfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="v_file",
            name="vf_file_no",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fms.newfile",
                to_field="file_no",
            ),
        ),
    ]
