# Generated by Django 4.1.5 on 2023-09-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fms", "0003_v_file_vf_file_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="section",
            fields=[
                ("sec_id", models.IntegerField(primary_key=True, serialize=False)),
                ("sec_user", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=20)),
            ],
        ),
    ]
