# Generated by Django 4.1.5 on 2023-09-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fms", "0004_section_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="section",
        ),
        migrations.DeleteModel(
            name="user",
        ),
        migrations.RemoveField(
            model_name="newfile",
            name="newfile_date",
        ),
        migrations.AddField(
            model_name="newfile",
            name="reciver",
            field=models.CharField(default="principal", max_length=20),
        ),
    ]
