# Generated by Django 4.1.5 on 2023-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fms", "0011_alter_newfile_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="newfile",
            name="sender",
            field=models.CharField(default="principal", max_length=10),
        ),
    ]
