# Generated by Django 4.1.5 on 2023-09-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fms", "0012_newfile_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newfile",
            name="sender",
        ),
        migrations.AddField(
            model_name="newfile",
            name="senders",
            field=models.CharField(default="admin", max_length=10),
        ),
    ]
